name: pull-request-ci

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:

    name: pull-request
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.9.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
